name: arctic-ocean-pco2
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - click
  - cartopy
  - cmcrameri
  - colorama
  - dask
  - Deprecated
  - docopt
  - geopandas
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter-book
  - jupyterbook-latex
  - jupyterlab
  - jupyternotify
  - jupytext
  - markdown
  - matplotlib
  - mystmd
  - nodejs
  - numpy==1.26
  - pandas
  - pytest
  - pytest-cov
  - python-dotenv
  - regionmask
  - scipy
  - seaborn
  - ruff
  - toml
  - tqdm
  - xarray
  - xarrayutils
  - xeofs
  - pip
  - pip:
    - mpl-axes-aligner
